apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: cassandra
    spec:
      containers:
      - image: "resouer/cassandra:latest"
        name: cassandra
        ports:
        - containerPort: 22
        - containerPort: 7001
        - containerPort: 9042
        - containerPort: 9160
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ZONE
          value: default.svc.35.185.135.130.xip.io
        resources:
          limits:
            memory: 2Gi
      restartPolicy: Always
