apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: chronos
  name: chronos
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: chronos
    spec:
      containers:
      - image: "resouer/chronos:latest"
        name: chronos
        ports:
        - containerPort: 22
        - containerPort: 7253
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
