apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ellis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: ellis
    spec:
      containers:
      - image: "resouer/ellis:latest"
        name: ellis
        ports:
        - containerPort: 22
        - containerPort: 80
        env:
        - name: ZONE
          value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
