apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ralf
spec:
  replicas: 1
  selector:
    matchLabels:
      service: ralf
  template:
    metadata:
      labels:
        service: ralf
        snmp: enabled
    spec:
      containers:
      - image: "resouer/ralf:latest"
        name: ralf
        ports:
        - containerPort: 22
        - containerPort: 10888
        env:
        - name: ZONE
          value: default.svc.35.185.135.130.xip.io
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
