apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sprout
spec:
  replicas: 1
  selector:
    matchLabels:
      service: sprout
  template:
    metadata:
      labels:
        service: sprout
        snmp: enabled
    spec:
      containers:
      - image: "resouer/sprout:latest"
        name: sprout
        ports:
        - containerPort: 22
        env:
        - name: ZONE
          value: default.svc.cluster.local
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
